---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cities":
    get:
      summary: returns a list of all cities
      tags:
      - Cities
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
              - id: 1
                name: Berlin
                created_at: '2021-12-09T04:50:21.272Z'
                updated_at: '2021-12-09T04:50:21.272Z'
              - id: 2
                name: Beirut
                created_at: '2021-12-09T04:50:21.274Z'
                updated_at: '2021-12-09T04:50:21.274Z'
              - id: 3
                name: Kingstown
                created_at: '2021-12-09T04:50:21.275Z'
                updated_at: '2021-12-09T04:50:21.275Z'
              - id: 4
                name: Monaco
                created_at: '2021-12-09T04:50:21.275Z'
                updated_at: '2021-12-09T04:50:21.275Z'
              - id: 5
                name: Hanoi
                created_at: '2021-12-09T04:50:21.276Z'
                updated_at: '2021-12-09T04:50:21.276Z'
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                  required:
                  - id
                  - name
                  - created_at
                  - updated_at
  "/api/v1/courses":
    get:
      summary: returns list with all courses
      tags:
      - Courses
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
              - id: 1
                title: Video gaming
                description: Laboriosam explicabo esse. Nesciunt quia magni. Et sit
                  et.
                instructor: Tania Hyatt V
                duration: 8
                created_at: '2021-12-09T04:50:21.346Z'
                updated_at: '2021-12-09T04:50:21.354Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/kgrhtpnmiv.jpeg
              - id: 2
                title: Surfing
                description: Dolorem in amet. Illo eos et. Voluptatem tempora doloribus.
                instructor: Johnnie Pfannerstill
                duration: 4
                created_at: '2021-12-09T04:50:21.373Z'
                updated_at: '2021-12-09T04:50:21.376Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/y31rkdqmxv.jpeg
              - id: 3
                title: Nordic skating
                description: Architecto non labore. Dignissimos omnis itaque. Excepturi
                  dolores ut.
                instructor: Donna Marquardt
                duration: 10
                created_at: '2021-12-09T04:50:21.386Z'
                updated_at: '2021-12-09T04:50:21.389Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/yiewcea2cv.jpeg
              - id: 4
                title: Bodybuilding
                description: Aut occaecati et. Est aperiam mollitia. Ut nulla excepturi.
                instructor: Sen. Angelo Stehr
                duration: 3
                created_at: '2021-12-09T04:50:21.395Z'
                updated_at: '2021-12-09T04:50:21.398Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/oiunqzzbdn.jpeg
              - id: 5
                title: tabletop games
                description: Rem perspiciatis dolor. Laboriosam nulla cumque. Dolor
                  doloremque voluptatem.
                instructor: Maximina Jerde
                duration: 1
                created_at: '2021-12-09T04:50:21.404Z'
                updated_at: '2021-12-09T04:50:21.407Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/og1nadl09c.jpeg
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    description:
                      type: string
                    instructor:
                      type: string
                    duration:
                      type: integer
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    course_image_url:
                      type: string
                  required:
                  - id
                  - title
                  - description
                  - instructor
                  - duration
                  - created_at
                  - updated_at
                  - course_image_url
                required: true
  "/api/v1/courses/{id}":
    get:
      summary: returns details for one course
      tags:
      - Courses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                id: 6
                title: Watching movies
                description: Omnis repudiandae delectus. Omnis architecto laudantium.
                  Cum alias quas.
                instructor: Eun Funk
                duration: 7
                created_at: '2021-12-09T04:50:21.457Z'
                updated_at: '2021-12-09T04:50:21.468Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/nzj882tcc9.jpeg
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  instructor:
                    type: string
                  duration:
                    type: integer
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  course_image_url:
                    type: string
                required:
                - id
                - title
                - description
                - instructor
                - duration
                - created_at
                - updated_at
                - course_image_url
  "/api/v1/sign_in":
    post:
      summary: creates a new session
      tags:
      - Sessions
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user exists:
                  value:
                    status: created
                    logged_in: true
                    user:
                      id: 4
                      username: ik4a0bkaew
                      name: Colby
                      created_at: '2021-12-09T04:50:21.546Z'
                      updated_at: '2021-12-09T04:50:21.546Z'
                when user does not exist:
                  value:
                    status: 401
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
              - username
  "/api/v1/signed_in":
    get:
      summary: return login status of user
      tags:
      - Sessions
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user is logged in:
                  value:
                    logged_in: true
                    user:
                      id: 14
                      username: k8ubplecox
                      name: Kitty
                      created_at: '2021-12-09T04:50:21.574Z'
                      updated_at: '2021-12-09T04:50:21.574Z'
                when user is not logged in:
                  value:
                    logged_in: false
              schema:
                type: object
                properties:
                  logged_in:
                    type: boolean
                required:
                - logged_in
  "/api/v1/sign_out":
    delete:
      summary: return logged-out status of user as true
      tags:
      - Sessions
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                status: 200
                logged_out: true
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  logged_out:
                    type: boolean
                required:
                - status
                - logged_out
  "/api/v1/users":
    post:
      summary: creates a new user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user exists:
                  value:
                    status: created
                    logged_in: true
                    user:
                      id: 32
                      username: p2ijqdzzxi
                      name: Ryan
                      created_at: '2021-12-09T04:50:21.636Z'
                      updated_at: '2021-12-09T04:50:21.636Z'
                when user does not exist:
                  value:
                    status: 401
                    error: This username already exists. Please Choose another one.
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
              required:
              - name
              - username
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
