---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cities":
    get:
      summary: returns a list of all cities
      tags:
      - Cities
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
              - id: 1
                name: Dublin
                created_at: '2021-12-09T19:49:22.719Z'
                updated_at: '2021-12-09T19:49:22.719Z'
              - id: 2
                name: Stockholm
                created_at: '2021-12-09T19:49:22.720Z'
                updated_at: '2021-12-09T19:49:22.720Z'
              - id: 3
                name: Honiara
                created_at: '2021-12-09T19:49:22.720Z'
                updated_at: '2021-12-09T19:49:22.720Z'
              - id: 4
                name: Zagreb
                created_at: '2021-12-09T19:49:22.721Z'
                updated_at: '2021-12-09T19:49:22.721Z'
              - id: 5
                name: Bujumbura
                created_at: '2021-12-09T19:49:22.721Z'
                updated_at: '2021-12-09T19:49:22.721Z'
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                  required:
                  - id
                  - name
                  - created_at
                  - updated_at
  "/api/v1/courses":
    get:
      summary: returns list with all courses
      tags:
      - Courses
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
              - id: 1
                title: Photography
                description: Corrupti illum voluptatem. Aperiam sequi iusto. Dolores
                  modi sit.
                instructor: Reginald Turner
                duration: 9
                created_at: '2021-12-09T19:49:22.769Z'
                updated_at: '2021-12-09T19:49:22.775Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/dspq9myo2v.jpeg
              - id: 2
                title: Board games
                description: Quibusdam rerum qui. Sapiente doloremque nihil. Illum
                  voluptas voluptas.
                instructor: Theron Bartoletti
                duration: 11
                created_at: '2021-12-09T19:49:22.781Z'
                updated_at: '2021-12-09T19:49:22.783Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/uhn1m9pbwc.jpeg
              - id: 3
                title: Genealogy
                description: Culpa reiciendis consequuntur. Aut eos facilis. Enim
                  delectus sunt.
                instructor: Thomasina Runolfsson
                duration: 5
                created_at: '2021-12-09T19:49:22.791Z'
                updated_at: '2021-12-09T19:49:22.793Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/5jp0zwyqhx.jpeg
              - id: 4
                title: Knitting
                description: Commodi atque odit. Possimus magnam quas. Et facilis
                  aut.
                instructor: Tarra Shanahan Ret.
                duration: 2
                created_at: '2021-12-09T19:49:22.798Z'
                updated_at: '2021-12-09T19:49:22.800Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/ibynj56n68.jpeg
              - id: 5
                title: Sudoku
                description: Voluptate expedita id. Aut labore similique. Quo aut
                  quis.
                instructor: Earl Spencer
                duration: 11
                created_at: '2021-12-09T19:49:22.804Z'
                updated_at: '2021-12-09T19:49:22.806Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/3nrb66p41b.jpeg
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    description:
                      type: string
                    instructor:
                      type: string
                    duration:
                      type: integer
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    course_image_url:
                      type: string
                  required:
                  - id
                  - title
                  - description
                  - instructor
                  - duration
                  - created_at
                  - updated_at
                  - course_image_url
                required: true
    post:
      summary: creates a new course
      tags:
      - Courses
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                message: Course successfully created
                status: created
                course:
                  id: 16
                  title: Web Development
                  description: Learn to build websites.
                  instructor: Mike Milano
                  duration: 12
                  created_at: '2021-12-09T19:49:22.973Z'
                  updated_at: '2021-12-09T19:49:22.976Z'
                  course_image_url: https://res.cloudinary.com/starsheriff/image/upload/39hh6jeb1o.jpeg
              schema:
                type: object
                properties:
                  course:
                    type: object
                  message:
                    type: string
                  status:
                    type: string
                required:
                - course
                - message
                - status
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                instructor:
                  type: string
                duration:
                  type: integer
                image:
                  type: binary
              required:
              - title
              - description
              - instructor
              - duration
              - image
        required: true
  "/api/v1/courses/{id}":
    get:
      summary: returns details for one course
      tags:
      - Courses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                id: 6
                title: Ice skating
                description: Provident sed error. Quidem eligendi omnis. Consequatur
                  magnam sit.
                instructor: Troy Schaden
                duration: 5
                created_at: '2021-12-09T19:49:22.854Z'
                updated_at: '2021-12-09T19:49:22.880Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/spedpz56bn.jpeg
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  instructor:
                    type: string
                  duration:
                    type: integer
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  course_image_url:
                    type: string
                required:
                - id
                - title
                - description
                - instructor
                - duration
                - created_at
                - updated_at
                - course_image_url
    delete:
      summary: deletes a course
      tags:
      - Courses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                course:
                  id: 17
                  title: Knitting
                  description: Esse eius reprehenderit. Rerum dolorum animi. Ut tempore
                    fugiat.
                  instructor: Larhonda Bauch
                  duration: 2
                  created_at: '2021-12-09T19:49:22.982Z'
                  updated_at: '2021-12-09T19:49:22.984Z'
                  course_image_url: https://res.cloudinary.com/starsheriff/image/upload/43tp0g593i.jpeg
                message: Course successfully deleted
                status: 200
              schema:
                type: object
                properties:
                  course:
                    type: object
                  message:
                    type: string
                  status:
                    type: integer
                required:
                - course
                - message
                - status
        '404':
          description: success
          content:
            application/json:
              example:
                message: Couldn't find Course with 'id'=1022
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
  "/api/v1/sign_in":
    post:
      summary: creates a new session
      tags:
      - Sessions
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user exists:
                  value:
                    status: created
                    logged_in: true
                    user:
                      id: 7
                      username: 0skwshs5fb
                      name: Edythe
                      created_at: '2021-12-09T19:49:23.082Z'
                      updated_at: '2021-12-09T19:49:23.082Z'
                when user does not exist:
                  value:
                    status: 401
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
              - username
        required: true
  "/api/v1/signed_in":
    get:
      summary: return login status of user
      tags:
      - Sessions
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user is logged in:
                  value:
                    logged_in: true
                    user:
                      id: 17
                      username: enxgb8nbkq
                      name: Rhett
                      created_at: '2021-12-09T19:49:23.106Z'
                      updated_at: '2021-12-09T19:49:23.106Z'
                when user is not logged in:
                  value:
                    logged_in: false
              schema:
                type: object
                properties:
                  logged_in:
                    type: boolean
                required:
                - logged_in
  "/api/v1/sign_out":
    delete:
      summary: return logged-out status of user as true
      tags:
      - Sessions
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                status: 200
                logged_out: true
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  logged_out:
                    type: boolean
                required:
                - status
                - logged_out
  "/api/v1/users":
    post:
      summary: creates a new user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user exists:
                  value:
                    status: created
                    logged_in: true
                    user:
                      id: 35
                      username: ays27185hl
                      name: Janelle
                      created_at: '2021-12-09T19:49:23.161Z'
                      updated_at: '2021-12-09T19:49:23.161Z'
                when user does not exist:
                  value:
                    status: 401
                    error: This username already exists. Please Choose another one.
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
              required:
              - name
              - username
        required: true
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
