---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cities":
    get:
      summary: returns a list of all cities
      tags:
      - Cities
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
              - id: 1
                name: Belmopan
                created_at: '2021-12-08T23:37:12.920Z'
                updated_at: '2021-12-08T23:37:12.920Z'
              - id: 2
                name: Brazzaville
                created_at: '2021-12-08T23:37:12.921Z'
                updated_at: '2021-12-08T23:37:12.921Z'
              - id: 3
                name: Managua
                created_at: '2021-12-08T23:37:12.921Z'
                updated_at: '2021-12-08T23:37:12.921Z'
              - id: 4
                name: Astana
                created_at: '2021-12-08T23:37:12.922Z'
                updated_at: '2021-12-08T23:37:12.922Z'
              - id: 5
                name: Ljubljana
                created_at: '2021-12-08T23:37:12.923Z'
                updated_at: '2021-12-08T23:37:12.923Z'
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                  required:
                  - id
                  - name
                  - created_at
                  - updated_at
  "/api/v1/users":
    post:
      summary: creates a new user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user does not exist:
                  value:
                    status: created
                    logged_in: true
                    user:
                      id: 5
                      username: qf7rw9mnof
                      name: Leonie
                      created_at: '2021-12-08T23:37:12.941Z'
                      updated_at: '2021-12-08T23:37:12.941Z'
                when user exists:
                  value:
                    status: 401
                    error: This username already exists. Please Choose another one.
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
              required:
              - name
              - username
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
