---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cities":
    get:
      summary: returns a list of all cities
      tags:
      - Cities
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
              - id: 1
                name: San Jose
                created_at: '2021-12-09T20:30:38.784Z'
                updated_at: '2021-12-09T20:30:38.784Z'
              - id: 2
                name: Moscow
                created_at: '2021-12-09T20:30:38.785Z'
                updated_at: '2021-12-09T20:30:38.785Z'
              - id: 3
                name: Chisinau
                created_at: '2021-12-09T20:30:38.786Z'
                updated_at: '2021-12-09T20:30:38.786Z'
              - id: 4
                name: Tallinn
                created_at: '2021-12-09T20:30:38.787Z'
                updated_at: '2021-12-09T20:30:38.787Z'
              - id: 5
                name: Singapore
                created_at: '2021-12-09T20:30:38.787Z'
                updated_at: '2021-12-09T20:30:38.787Z'
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                  required:
                  - id
                  - name
                  - created_at
                  - updated_at
  "/api/v1/courses":
    get:
      summary: returns list with all courses
      tags:
      - Courses
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
              - id: 1
                title: Knitting
                description: Iure et qui. Fuga est ab. Tenetur error possimus.
                instructor: Brett Yundt I
                duration: 5
                created_at: '2021-12-09T20:30:38.835Z'
                updated_at: '2021-12-09T20:30:38.840Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/qawlq89w0p.jpeg
              - id: 2
                title: Creative writing
                description: Est aliquid aut. Voluptate non ad. Mollitia dolores est.
                instructor: Dario Hyatt
                duration: 5
                created_at: '2021-12-09T20:30:38.846Z'
                updated_at: '2021-12-09T20:30:38.848Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/p1vsdsn79t.jpeg
              - id: 3
                title: Writing
                description: Nemo reiciendis dolores. Et in iste. Reiciendis ad qui.
                instructor: Kory Harber
                duration: 11
                created_at: '2021-12-09T20:30:38.853Z'
                updated_at: '2021-12-09T20:30:38.855Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/qxgnb7qyfp.jpeg
              - id: 4
                title: Quilting
                description: Sit rerum est. Dolorum qui sequi. Laudantium eum et.
                instructor: Darwin Schimmel
                duration: 10
                created_at: '2021-12-09T20:30:38.860Z'
                updated_at: '2021-12-09T20:30:38.862Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/avfr6q49f2.jpeg
              - id: 5
                title: Skiing
                description: Molestiae accusantium dolores. Molestiae laborum est.
                  Expedita a quam.
                instructor: Princess Corwin
                duration: 9
                created_at: '2021-12-09T20:30:38.866Z'
                updated_at: '2021-12-09T20:30:38.868Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/sum735soyd.jpeg
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    description:
                      type: string
                    instructor:
                      type: string
                    duration:
                      type: integer
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    course_image_url:
                      type: string
                  required:
                  - id
                  - title
                  - description
                  - instructor
                  - duration
                  - created_at
                  - updated_at
                  - course_image_url
                required: true
    post:
      summary: creates a new course
      tags:
      - Courses
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                message: Course successfully created
                status: created
                course:
                  id: 16
                  title: Web Development
                  description: Learn to build websites.
                  instructor: Mike Milano
                  duration: 12
                  created_at: '2021-12-09T20:30:39.031Z'
                  updated_at: '2021-12-09T20:30:39.034Z'
                  course_image_url: https://res.cloudinary.com/starsheriff/image/upload/0gkpyx2vvn.jpeg
              schema:
                type: object
                properties:
                  course:
                    type: object
                  message:
                    type: string
                  status:
                    type: string
                required:
                - course
                - message
                - status
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                instructor:
                  type: string
                duration:
                  type: integer
                image:
                  type: binary
              required:
              - title
              - description
              - instructor
              - duration
              - image
        required: true
  "/api/v1/courses/{id}":
    get:
      summary: returns details for one course
      tags:
      - Courses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                id: 6
                title: Running
                description: Eos minus quia. Omnis tenetur eius. Facilis ipsa excepturi.
                instructor: Noma Conn DVM
                duration: 5
                created_at: '2021-12-09T20:30:38.937Z'
                updated_at: '2021-12-09T20:30:38.940Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/9x7hiiw6yc.jpeg
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  instructor:
                    type: string
                  duration:
                    type: integer
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  course_image_url:
                    type: string
                required:
                - id
                - title
                - description
                - instructor
                - duration
                - created_at
                - updated_at
                - course_image_url
    delete:
      summary: deletes a course
      tags:
      - Courses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                course:
                  id: 17
                  title: Drawing
                  description: Adipisci aliquid animi. Unde eum nihil. Repudiandae
                    sed nobis.
                  instructor: Yael Legros
                  duration: 4
                  created_at: '2021-12-09T20:30:39.040Z'
                  updated_at: '2021-12-09T20:30:39.042Z'
                  course_image_url: https://res.cloudinary.com/starsheriff/image/upload/cv46bownil.jpeg
                message: Course successfully deleted
                status: 200
              schema:
                type: object
                properties:
                  course:
                    type: object
                  message:
                    type: string
                  status:
                    type: integer
                required:
                - course
                - message
                - status
        '404':
          description: success
          content:
            application/json:
              example:
                message: Couldn't find Course with 'id'=1022
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
  "/api/v1/reservations":
    get:
      summary: returns list with all reservations
      tags:
      - Reservations
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
              - user: Marianna
                course: Skimboarding
                city: Riga
                date: '2022-11-24'
                id: 1
                created_at: '2021-12-09T20:30:39.158Z'
                updated_at: '2021-12-09T20:30:39.158Z'
              - user: Marianna
                course: LARPing
                city: Libreville
                date: '2021-12-27'
                id: 2
                created_at: '2021-12-09T20:30:39.168Z'
                updated_at: '2021-12-09T20:30:39.168Z'
              - user: Marianna
                course: Jigsaw puzzles
                city: Kuala Lumpur
                date: '2022-06-25'
                id: 3
                created_at: '2021-12-09T20:30:39.177Z'
                updated_at: '2021-12-09T20:30:39.177Z'
              - user: Marianna
                course: Wood carving
                city: Tallinn
                date: '2022-09-05'
                id: 4
                created_at: '2021-12-09T20:30:39.185Z'
                updated_at: '2021-12-09T20:30:39.185Z'
              - user: Marianna
                course: Rock climbing
                city: Freetown
                date: '2022-09-17'
                id: 5
                created_at: '2021-12-09T20:30:39.195Z'
                updated_at: '2021-12-09T20:30:39.195Z'
              schema:
                type: array
                items:
                  type: object
                  properties:
                    user:
                      type: string
                    course:
                      type: string
                    city:
                      type: string
                    date:
                      type: string
                    id:
                      type: integer
                    created_at:
                      type: string
                    updated_at:
                      type: string
                  required:
                  - user
                  - course
                  - city
                  - date
                  - id
                  - created_at
                  - updated_at
                required: true
    post:
      summary: creates a new course
      tags:
      - Reservations
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                reservation:
                  user: Daniele
                  course: Kabaddi
                  city: Bridgetown
                  date: '2021-12-10'
                  id: 11
                  created_at: '2021-12-09T20:30:39.403Z'
                  updated_at: '2021-12-09T20:30:39.403Z'
                message: Reservation created successfully
                status: 200
              schema:
                type: object
                properties:
                  reservation:
                    type: object
                    properties:
                      user:
                        type: string
                      course:
                        type: string
                      city:
                        type: string
                      date:
                        type: string
                      id:
                        type: integer
                      created_at:
                        type: string
                      updated_at:
                        type: string
                    required:
                    - user
                    - course
                    - city
                    - date
                    - id
                    - created_at
                    - updated_at
                  message:
                    type: string
                  status:
                    type: integer
                required:
                - reservation
                - message
                - status
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                user_id:
                  type: integer
                course_id:
                  type: integer
                city_id:
                  type: integer
              required:
              - date
              - user_id
              - course_id
              - city_id
        required: true
  "/api/v1/sign_in":
    post:
      summary: creates a new session
      tags:
      - Sessions
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user exists:
                  value:
                    status: created
                    logged_in: true
                    user:
                      id: 17
                      username: ofwof7of9t
                      name: Isaac
                      created_at: '2021-12-09T20:30:39.407Z'
                      updated_at: '2021-12-09T20:30:39.407Z'
                when user does not exist:
                  value:
                    status: 401
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
              - username
        required: true
  "/api/v1/signed_in":
    get:
      summary: return login status of user
      tags:
      - Sessions
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user is logged in:
                  value:
                    logged_in: true
                    user:
                      id: 27
                      username: iaadh5vpp8
                      name: Alvin
                      created_at: '2021-12-09T20:30:39.432Z'
                      updated_at: '2021-12-09T20:30:39.432Z'
                when user is not logged in:
                  value:
                    logged_in: false
              schema:
                type: object
                properties:
                  logged_in:
                    type: boolean
                required:
                - logged_in
  "/api/v1/sign_out":
    delete:
      summary: return logged-out status of user as true
      tags:
      - Sessions
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                status: 200
                logged_out: true
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  logged_out:
                    type: boolean
                required:
                - status
                - logged_out
  "/api/v1/users":
    post:
      summary: creates a new user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user exists:
                  value:
                    status: created
                    logged_in: true
                    user:
                      id: 45
                      username: i4adu59246
                      name: Kathyrn
                      created_at: '2021-12-09T20:30:39.490Z'
                      updated_at: '2021-12-09T20:30:39.490Z'
                when user does not exist:
                  value:
                    status: 401
                    error: This username already exists. Please Choose another one.
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
              required:
              - name
              - username
        required: true
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
