---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cities":
    get:
      summary: returns a list of all cities
      tags:
      - Cities
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
              - id: 1
                name: Kigali
                created_at: '2021-12-08T21:29:51.772Z'
                updated_at: '2021-12-08T21:29:51.772Z'
              - id: 2
                name: Kampala
                created_at: '2021-12-08T21:29:51.774Z'
                updated_at: '2021-12-08T21:29:51.774Z'
              - id: 3
                name: Budapest
                created_at: '2021-12-08T21:29:51.774Z'
                updated_at: '2021-12-08T21:29:51.774Z'
              - id: 4
                name: Dakar
                created_at: '2021-12-08T21:29:51.775Z'
                updated_at: '2021-12-08T21:29:51.775Z'
              - id: 5
                name: Valletta
                created_at: '2021-12-08T21:29:51.775Z'
                updated_at: '2021-12-08T21:29:51.775Z'
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                  required:
                  - id
                  - name
                  - created_at
                  - updated_at
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
