---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cities":
    get:
      summary: returns a list of all cities
      tags:
      - Cities
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
              - id: 1
                name: Tegucigalpa
                created_at: '2021-12-09T20:10:04.567Z'
                updated_at: '2021-12-09T20:10:04.567Z'
              - id: 2
                name: Warsaw
                created_at: '2021-12-09T20:10:04.568Z'
                updated_at: '2021-12-09T20:10:04.568Z'
              - id: 3
                name: Yaounde
                created_at: '2021-12-09T20:10:04.568Z'
                updated_at: '2021-12-09T20:10:04.568Z'
              - id: 4
                name: Port Louis
                created_at: '2021-12-09T20:10:04.569Z'
                updated_at: '2021-12-09T20:10:04.569Z'
              - id: 5
                name: Vilnius
                created_at: '2021-12-09T20:10:04.569Z'
                updated_at: '2021-12-09T20:10:04.569Z'
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                  required:
                  - id
                  - name
                  - created_at
                  - updated_at
  "/api/v1/courses":
    get:
      summary: returns list with all courses
      tags:
      - Courses
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
              - id: 1
                title: Pottery
                description: Earum eum ipsum. Reprehenderit aut alias. Non molestiae
                  fuga.
                instructor: Kennith Keeling I
                duration: 3
                created_at: '2021-12-09T20:10:04.618Z'
                updated_at: '2021-12-09T20:10:04.624Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/w0mar3oy2c.jpeg
              - id: 2
                title: Candle making
                description: Vitae et maiores. Mollitia consequatur et. Rem nesciunt
                  eveniet.
                instructor: Kathern Ward Ret.
                duration: 8
                created_at: '2021-12-09T20:10:04.629Z'
                updated_at: '2021-12-09T20:10:04.632Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/27gmrdhg6v.jpeg
              - id: 3
                title: Geocaching
                description: Dignissimos aut molestiae. Vel et et. Voluptatum non
                  officia.
                instructor: Alba Wisozk
                duration: 10
                created_at: '2021-12-09T20:10:04.636Z'
                updated_at: '2021-12-09T20:10:04.638Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/3xw4svg4h1.jpeg
              - id: 4
                title: Digital arts
                description: Minus ea quia. Modi rerum temporibus. Et sit est.
                instructor: Jeane Conn IV
                duration: 1
                created_at: '2021-12-09T20:10:04.643Z'
                updated_at: '2021-12-09T20:10:04.645Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/rwzr1t6oz6.jpeg
              - id: 5
                title: Mycology
                description: Repellat doloribus blanditiis. Non nisi sequi. Culpa
                  asperiores eos.
                instructor: The Hon. Elaine Boyer
                duration: 0
                created_at: '2021-12-09T20:10:04.650Z'
                updated_at: '2021-12-09T20:10:04.652Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/5y2b9hlm6y.jpeg
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    description:
                      type: string
                    instructor:
                      type: string
                    duration:
                      type: integer
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    course_image_url:
                      type: string
                  required:
                  - id
                  - title
                  - description
                  - instructor
                  - duration
                  - created_at
                  - updated_at
                  - course_image_url
                required: true
    post:
      summary: creates a new course
      tags:
      - Courses
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                message: Course successfully created
                status: created
                course:
                  id: 16
                  title: Web Development
                  description: Learn to build websites.
                  instructor: Mike Milano
                  duration: 12
                  created_at: '2021-12-09T20:10:04.819Z'
                  updated_at: '2021-12-09T20:10:04.821Z'
                  course_image_url: https://res.cloudinary.com/starsheriff/image/upload/11vsvb2fqs.jpeg
              schema:
                type: object
                properties:
                  course:
                    type: object
                  message:
                    type: string
                  status:
                    type: string
                required:
                - course
                - message
                - status
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                instructor:
                  type: string
                duration:
                  type: integer
                image:
                  type: binary
              required:
              - title
              - description
              - instructor
              - duration
              - image
        required: true
  "/api/v1/courses/{id}":
    get:
      summary: returns details for one course
      tags:
      - Courses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                id: 6
                title: Rappelling
                description: Non hic delectus. Quidem vero quia. Alias qui voluptatem.
                instructor: Victor Padberg
                duration: 3
                created_at: '2021-12-09T20:10:04.721Z'
                updated_at: '2021-12-09T20:10:04.723Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/63qnhjxtov.jpeg
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  instructor:
                    type: string
                  duration:
                    type: integer
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  course_image_url:
                    type: string
                required:
                - id
                - title
                - description
                - instructor
                - duration
                - created_at
                - updated_at
                - course_image_url
    delete:
      summary: deletes a course
      tags:
      - Courses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                course:
                  id: 17
                  title: Juggling
                  description: Nobis modi nulla. Fugit cupiditate qui. Sit consequuntur
                    rem.
                  instructor: Lon Hane
                  duration: 10
                  created_at: '2021-12-09T20:10:04.832Z'
                  updated_at: '2021-12-09T20:10:04.834Z'
                  course_image_url: https://res.cloudinary.com/starsheriff/image/upload/tpuax4xznu.jpeg
                message: Course successfully deleted
                status: 200
              schema:
                type: object
                properties:
                  course:
                    type: object
                  message:
                    type: string
                  status:
                    type: integer
                required:
                - course
                - message
                - status
        '404':
          description: success
          content:
            application/json:
              example:
                message: Couldn't find Course with 'id'=1022
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
  "/api/v1/reservations":
    get:
      summary: returns list with all reservations
      tags:
      - Reservations
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
              - user: Ione
                course: Skydiving
                city: Georgetown
                date: '2022-03-22'
                id: 1
                created_at: '2021-12-09T20:10:04.949Z'
                updated_at: '2021-12-09T20:10:04.949Z'
              - user: Ione
                course: Inline skating
                city: Tallinn
                date: '2022-04-28'
                id: 2
                created_at: '2021-12-09T20:10:04.960Z'
                updated_at: '2021-12-09T20:10:04.960Z'
              - user: Ione
                course: Electronics
                city: Islamabad
                date: '2022-10-27'
                id: 3
                created_at: '2021-12-09T20:10:04.968Z'
                updated_at: '2021-12-09T20:10:04.968Z'
              - user: Ione
                course: Cabaret
                city: Vatican City
                date: '2022-10-03'
                id: 4
                created_at: '2021-12-09T20:10:04.977Z'
                updated_at: '2021-12-09T20:10:04.977Z'
              - user: Ione
                course: Acting
                city: Moroni
                date: '2022-05-25'
                id: 5
                created_at: '2021-12-09T20:10:04.985Z'
                updated_at: '2021-12-09T20:10:04.985Z'
              schema:
                type: array
                items:
                  type: object
                  properties:
                    user:
                      type: string
                    course:
                      type: string
                    city:
                      type: string
                    date:
                      type: string
                    id:
                      type: integer
                    created_at:
                      type: string
                    updated_at:
                      type: string
                  required:
                  - user
                  - course
                  - city
                  - date
                  - id
                  - created_at
                  - updated_at
                required: true
  "/api/v1/sign_in":
    post:
      summary: creates a new session
      tags:
      - Sessions
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user exists:
                  value:
                    status: created
                    logged_in: true
                    user:
                      id: 12
                      username: 3id9pb3f52
                      name: Ellsworth
                      created_at: '2021-12-09T20:10:05.073Z'
                      updated_at: '2021-12-09T20:10:05.073Z'
                when user does not exist:
                  value:
                    status: 401
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
              - username
        required: true
  "/api/v1/signed_in":
    get:
      summary: return login status of user
      tags:
      - Sessions
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user is logged in:
                  value:
                    logged_in: true
                    user:
                      id: 22
                      username: txmtj9vdl7
                      name: Mike
                      created_at: '2021-12-09T20:10:05.096Z'
                      updated_at: '2021-12-09T20:10:05.096Z'
                when user is not logged in:
                  value:
                    logged_in: false
              schema:
                type: object
                properties:
                  logged_in:
                    type: boolean
                required:
                - logged_in
  "/api/v1/sign_out":
    delete:
      summary: return logged-out status of user as true
      tags:
      - Sessions
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                status: 200
                logged_out: true
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  logged_out:
                    type: boolean
                required:
                - status
                - logged_out
  "/api/v1/users":
    post:
      summary: creates a new user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user exists:
                  value:
                    status: created
                    logged_in: true
                    user:
                      id: 40
                      username: 1uupfv0tcg
                      name: Debbie
                      created_at: '2021-12-09T20:10:05.149Z'
                      updated_at: '2021-12-09T20:10:05.149Z'
                when user does not exist:
                  value:
                    status: 401
                    error: This username already exists. Please Choose another one.
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
              required:
              - name
              - username
        required: true
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
