---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cities":
    get:
      summary: returns a list of all cities
      tags:
      - Cities
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
              - id: 1
                name: Thimphu
                created_at: '2021-12-09T01:04:16.504Z'
                updated_at: '2021-12-09T01:04:16.504Z'
              - id: 2
                name: Djibouti
                created_at: '2021-12-09T01:04:16.505Z'
                updated_at: '2021-12-09T01:04:16.505Z'
              - id: 3
                name: Canberra
                created_at: '2021-12-09T01:04:16.506Z'
                updated_at: '2021-12-09T01:04:16.506Z'
              - id: 4
                name: Pyongyang
                created_at: '2021-12-09T01:04:16.506Z'
                updated_at: '2021-12-09T01:04:16.506Z'
              - id: 5
                name: Minsk
                created_at: '2021-12-09T01:04:16.507Z'
                updated_at: '2021-12-09T01:04:16.507Z'
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                  required:
                  - id
                  - name
                  - created_at
                  - updated_at
  "/api/v1/sign_in":
    post:
      summary: creates a new session
      tags:
      - Sessions
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user exists:
                  value:
                    status: created
                    logged_in: true
                    user:
                      id: 2
                      username: 9mmt9krqtq
                      name: William
                      created_at: '2021-12-09T01:04:16.517Z'
                      updated_at: '2021-12-09T01:04:16.517Z'
                when user does not exist:
                  value:
                    status: 401
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
              - username
  "/api/v1/users":
    post:
      summary: creates a new user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user does not exist:
                  value:
                    status: created
                    logged_in: true
                    user:
                      id: 15
                      username: rg0na6184u
                      name: Annamae
                      created_at: '2021-12-09T01:04:16.560Z'
                      updated_at: '2021-12-09T01:04:16.560Z'
                when user exists:
                  value:
                    status: 401
                    error: This username already exists. Please Choose another one.
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
              required:
              - name
              - username
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
