---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cities":
    get:
      summary: returns a list of all cities
      tags:
      - Cities
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
              - id: 1
                name: Lusaka
                created_at: '2021-12-09T04:48:57.065Z'
                updated_at: '2021-12-09T04:48:57.065Z'
              - id: 2
                name: Bratislava
                created_at: '2021-12-09T04:48:57.067Z'
                updated_at: '2021-12-09T04:48:57.067Z'
              - id: 3
                name: Dili
                created_at: '2021-12-09T04:48:57.067Z'
                updated_at: '2021-12-09T04:48:57.067Z'
              - id: 4
                name: Bamako
                created_at: '2021-12-09T04:48:57.068Z'
                updated_at: '2021-12-09T04:48:57.068Z'
              - id: 5
                name: Helsinki
                created_at: '2021-12-09T04:48:57.068Z'
                updated_at: '2021-12-09T04:48:57.068Z'
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                  required:
                  - id
                  - name
                  - created_at
                  - updated_at
  "/api/v1/courses":
    get:
      summary: returns list with all courses
      tags:
      - Courses
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
              - id: 1
                title: Singing
                description: Quos adipisci quidem. Eveniet hic perspiciatis. Ducimus
                  omnis tenetur.
                instructor: Msgr. Frederick Jast
                duration: 10
                created_at: '2021-12-09T04:48:57.118Z'
                updated_at: '2021-12-09T04:48:57.123Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/khc3be3z6u.jpeg
              - id: 2
                title: Worldbuilding
                description: Eum itaque asperiores. Voluptas odio nobis. Voluptas
                  repudiandae optio.
                instructor: Lilia Goyette
                duration: 8
                created_at: '2021-12-09T04:48:57.129Z'
                updated_at: '2021-12-09T04:48:57.132Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/ryx799wkei.jpeg
              - id: 3
                title: Board games
                description: Hic voluptatem iure. Aut nesciunt non. Vel illo saepe.
                instructor: Flora Rippin
                duration: 5
                created_at: '2021-12-09T04:48:57.137Z'
                updated_at: '2021-12-09T04:48:57.139Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/88uainb815.jpeg
              - id: 4
                title: Water sports
                description: Occaecati doloribus blanditiis. Quibusdam totam et. Dolores
                  perferendis id.
                instructor: Daryl Collier
                duration: 8
                created_at: '2021-12-09T04:48:57.144Z'
                updated_at: '2021-12-09T04:48:57.146Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/p1zs2mblz1.jpeg
              - id: 5
                title: Board games
                description: Aliquid doloribus sequi. Sit quo qui. Deleniti magni
                  repellat.
                instructor: Woodrow Mohr
                duration: 8
                created_at: '2021-12-09T04:48:57.151Z'
                updated_at: '2021-12-09T04:48:57.153Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/z5p9nayfjb.jpeg
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    description:
                      type: string
                    instructor:
                      type: string
                    duration:
                      type: integer
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    course_image_url:
                      type: string
                  required:
                  - id
                  - title
                  - description
                  - instructor
                  - duration
                  - created_at
                  - updated_at
                  - course_image_url
                required: true
  "/api/v1/courses/{id}":
    get:
      summary: returns details for one course
      tags:
      - Courses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                id: 6
                title: Ghost hunting
                description: Facere quas amet. Non ut et. Nihil voluptatem consequatur.
                instructor: Jan Effertz
                duration: 3
                created_at: '2021-12-09T04:48:57.197Z'
                updated_at: '2021-12-09T04:48:57.206Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/1gqtiikl7w.jpeg
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  instructor:
                    type: string
                  duration:
                    type: integer
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  course_image_url:
                    type: string
                required:
                - id
                - title
                - description
                - instructor
                - duration
                - created_at
                - updated_at
                - course_image_url
  "/api/v1/sign_in":
    post:
      summary: creates a new session
      tags:
      - Sessions
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user exists:
                  value:
                    status: created
                    logged_in: true
                    user:
                      id: 4
                      username: xc1648qbmh
                      name: Helaine
                      created_at: '2021-12-09T04:48:57.276Z'
                      updated_at: '2021-12-09T04:48:57.276Z'
                when user does not exist:
                  value:
                    status: 401
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
              - username
  "/api/v1/signed_in":
    get:
      summary: return login status of user
      tags:
      - Sessions
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user is logged in:
                  value:
                    logged_in: true
                    user:
                      id: 14
                      username: 55v7zue6ww
                      name: Joe
                      created_at: '2021-12-09T04:48:57.300Z'
                      updated_at: '2021-12-09T04:48:57.300Z'
                when user is not logged in:
                  value:
                    logged_in: false
              schema:
                type: object
                properties:
                  logged_in:
                    type: boolean
                required:
                - logged_in
  "/api/v1/sign_out":
    delete:
      summary: return logged-out status of user as true
      tags:
      - Sessions
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                status: 200
                logged_out: true
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  logged_out:
                    type: boolean
                required:
                - status
                - logged_out
  "/api/v1/users":
    post:
      summary: creates a new user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user exists:
                  value:
                    status: created
                    logged_in: true
                    user:
                      id: 32
                      username: mi8ndpatub
                      name: Clinton
                      created_at: '2021-12-09T04:48:57.354Z'
                      updated_at: '2021-12-09T04:48:57.354Z'
                when user does not exist:
                  value:
                    status: 401
                    error: This username already exists. Please Choose another one.
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
              required:
              - name
              - username
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
