---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cities":
    get:
      summary: returns a list of all cities
      tags:
      - Cities
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
              - id: 1
                name: Freetown
                created_at: '2021-12-09T16:17:00.036Z'
                updated_at: '2021-12-09T16:17:00.036Z'
              - id: 2
                name: Nuku'alofa
                created_at: '2021-12-09T16:17:00.037Z'
                updated_at: '2021-12-09T16:17:00.037Z'
              - id: 3
                name: Skopje
                created_at: '2021-12-09T16:17:00.038Z'
                updated_at: '2021-12-09T16:17:00.038Z'
              - id: 4
                name: Riga
                created_at: '2021-12-09T16:17:00.038Z'
                updated_at: '2021-12-09T16:17:00.038Z'
              - id: 5
                name: Canberra
                created_at: '2021-12-09T16:17:00.039Z'
                updated_at: '2021-12-09T16:17:00.039Z'
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                  required:
                  - id
                  - name
                  - created_at
                  - updated_at
  "/api/v1/courses":
    get:
      summary: returns list with all courses
      tags:
      - Courses
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
              - id: 1
                title: Genealogy
                description: Assumenda ad est. Ratione illo consequatur. Ullam aut
                  ut.
                instructor: Weston Walker DC
                duration: 9
                created_at: '2021-12-09T16:17:00.092Z'
                updated_at: '2021-12-09T16:17:00.097Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/xtxlyh65ei.jpeg
              - id: 2
                title: Mycology
                description: Sequi nihil officiis. Quis consectetur qui. Sequi fugit
                  commodi.
                instructor: Gary Kuhic
                duration: 10
                created_at: '2021-12-09T16:17:00.104Z'
                updated_at: '2021-12-09T16:17:00.106Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/2psm6f2v3w.jpeg
              - id: 3
                title: Crocheting
                description: Rerum provident earum. Similique deserunt at. Ut placeat
                  molestiae.
                instructor: Dannielle McGlynn
                duration: 8
                created_at: '2021-12-09T16:17:00.111Z'
                updated_at: '2021-12-09T16:17:00.113Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/2gqqai88aa.jpeg
              - id: 4
                title: Candle making
                description: Alias dolores eos. Qui aut iure. Alias quam voluptatem.
                instructor: Joellen Erdman DVM
                duration: 5
                created_at: '2021-12-09T16:17:00.118Z'
                updated_at: '2021-12-09T16:17:00.120Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/alsbueup1f.jpeg
              - id: 5
                title: Sailing
                description: Distinctio natus voluptatem. Sint et in. Et enim commodi.
                instructor: Huey Hyatt
                duration: 1
                created_at: '2021-12-09T16:17:00.125Z'
                updated_at: '2021-12-09T16:17:00.127Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/7pzy1mkd62.jpeg
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    description:
                      type: string
                    instructor:
                      type: string
                    duration:
                      type: integer
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    course_image_url:
                      type: string
                  required:
                  - id
                  - title
                  - description
                  - instructor
                  - duration
                  - created_at
                  - updated_at
                  - course_image_url
                required: true
    post:
      summary: creates a new course
      tags:
      - Courses
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                message: Course successfully created
                status: created
                course:
                  id: 16
                  title: Web Development
                  description: Learn to build websites.
                  instructor: Mike Milano
                  duration: 12
                  created_at: '2021-12-09T16:17:00.301Z'
                  updated_at: '2021-12-09T16:17:00.303Z'
                  course_image_url: https://res.cloudinary.com/starsheriff/image/upload/65y7vla5yp.jpeg
              schema:
                type: object
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                instructor:
                  type: string
                duration:
                  type: integer
                image:
                  type: binary
              required:
              - title
              - description
              - instructor
              - duration
              - image
        required: true
  "/api/v1/courses/{id}":
    get:
      summary: returns details for one course
      tags:
      - Courses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                id: 6
                title: Reading
                description: Voluptate natus aliquam. Facere suscipit blanditiis.
                  Et praesentium sit.
                instructor: Ardith Kovacek
                duration: 6
                created_at: '2021-12-09T16:17:00.177Z'
                updated_at: '2021-12-09T16:17:00.200Z'
                course_image_url: https://res.cloudinary.com/starsheriff/image/upload/9f3n86ge8o.jpeg
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  instructor:
                    type: string
                  duration:
                    type: integer
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  course_image_url:
                    type: string
                required:
                - id
                - title
                - description
                - instructor
                - duration
                - created_at
                - updated_at
                - course_image_url
    delete:
      summary: deletes a course
      tags:
      - Courses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                status: created
                logged_in: true
                user:
                  id: 5
                  username: nq4fekgfb4
                  name: Lakesha
                  created_at: '2021-12-09T16:17:00.343Z'
                  updated_at: '2021-12-09T16:17:00.343Z'
              schema:
                type: object
  "/api/v1/sign_in":
    post:
      summary: creates a new session
      tags:
      - Sessions
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user exists:
                  value:
                    status: created
                    logged_in: true
                    user:
                      id: 6
                      username: gjw4wnaxtw
                      name: Marni
                      created_at: '2021-12-09T16:17:00.362Z'
                      updated_at: '2021-12-09T16:17:00.362Z'
                when user does not exist:
                  value:
                    status: 401
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
              - username
        required: true
  "/api/v1/signed_in":
    get:
      summary: return login status of user
      tags:
      - Sessions
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user is logged in:
                  value:
                    logged_in: true
                    user:
                      id: 16
                      username: ibvgkjfcrt
                      name: Bessie
                      created_at: '2021-12-09T16:17:00.386Z'
                      updated_at: '2021-12-09T16:17:00.386Z'
                when user is not logged in:
                  value:
                    logged_in: false
              schema:
                type: object
                properties:
                  logged_in:
                    type: boolean
                required:
                - logged_in
  "/api/v1/sign_out":
    delete:
      summary: return logged-out status of user as true
      tags:
      - Sessions
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                status: 200
                logged_out: true
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  logged_out:
                    type: boolean
                required:
                - status
                - logged_out
  "/api/v1/users":
    post:
      summary: creates a new user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                when user exists:
                  value:
                    status: created
                    logged_in: true
                    user:
                      id: 34
                      username: hahlpa30n9
                      name: Salvador
                      created_at: '2021-12-09T16:17:00.441Z'
                      updated_at: '2021-12-09T16:17:00.441Z'
                when user does not exist:
                  value:
                    status: 401
                    error: This username already exists. Please Choose another one.
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
              required:
              - name
              - username
        required: true
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
